# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PassengerApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!

  # Pods for PassengerApp

  pod 'GoogleMaps', '2.7.0'
  pod 'SDWebImage/GIF'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'CardIO'
  pod 'SinchRTC', '~> 3.12.7'
  pod 'CropViewController'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'IQKeyboardManagerSwift'
  pod "CreditCardValidator"
  pod 'Xendit', '3.0.0-beta'
  pod 'NVActivityIndicatorView'
  pod 'BFPaperButton'
  pod 'BEMCheckBox'
  pod 'KTCenterFlowLayout'
  pod "MXParallaxHeader"
  pod "CMSwitchView"
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Bagel', '~>  1.4.0'
  pod 'MarqueeLabel'


  target 'PassengerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'YES'
    puts "CLANG_WARN_UNGUARDED_AVAILABILITY was set to YES for all pods"
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
